// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package employee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	EmployeesSort(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Employees, error)
	TheOldest(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Employee, error)
	TheRichest(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Employee, error)
	MeanSalary(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Salary, error)
	MedianSalary(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Salary, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) EmployeesSort(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Employees, error) {
	out := new(Employees)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/EmployeesSort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) TheOldest(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/TheOldest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) TheRichest(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/TheRichest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) MeanSalary(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Salary, error) {
	out := new(Salary)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/MeanSalary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) MedianSalary(ctx context.Context, in *Imitator, opts ...grpc.CallOption) (*Salary, error) {
	out := new(Salary)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/MedianSalary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility
type EmployeeServiceServer interface {
	EmployeesSort(context.Context, *Filter) (*Employees, error)
	TheOldest(context.Context, *Imitator) (*Employee, error)
	TheRichest(context.Context, *Imitator) (*Employee, error)
	MeanSalary(context.Context, *Imitator) (*Salary, error)
	MedianSalary(context.Context, *Imitator) (*Salary, error)
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (UnimplementedEmployeeServiceServer) EmployeesSort(context.Context, *Filter) (*Employees, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmployeesSort not implemented")
}
func (UnimplementedEmployeeServiceServer) TheOldest(context.Context, *Imitator) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TheOldest not implemented")
}
func (UnimplementedEmployeeServiceServer) TheRichest(context.Context, *Imitator) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TheRichest not implemented")
}
func (UnimplementedEmployeeServiceServer) MeanSalary(context.Context, *Imitator) (*Salary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeanSalary not implemented")
}
func (UnimplementedEmployeeServiceServer) MedianSalary(context.Context, *Imitator) (*Salary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MedianSalary not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_EmployeesSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).EmployeesSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/EmployeesSort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).EmployeesSort(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_TheOldest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Imitator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).TheOldest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/TheOldest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).TheOldest(ctx, req.(*Imitator))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_TheRichest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Imitator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).TheRichest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/TheRichest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).TheRichest(ctx, req.(*Imitator))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_MeanSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Imitator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).MeanSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/MeanSalary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).MeanSalary(ctx, req.(*Imitator))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_MedianSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Imitator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).MedianSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/MedianSalary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).MedianSalary(ctx, req.(*Imitator))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmployeesSort",
			Handler:    _EmployeeService_EmployeesSort_Handler,
		},
		{
			MethodName: "TheOldest",
			Handler:    _EmployeeService_TheOldest_Handler,
		},
		{
			MethodName: "TheRichest",
			Handler:    _EmployeeService_TheRichest_Handler,
		},
		{
			MethodName: "MeanSalary",
			Handler:    _EmployeeService_MeanSalary_Handler,
		},
		{
			MethodName: "MedianSalary",
			Handler:    _EmployeeService_MedianSalary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/employee.proto",
}
